sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --trace #--quiet 

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "OUUS+XWiPOavLiwTONez6VW+z1nh78+sOX5SaWkHF8pkxIarYvPp8rv0pbKD7znS/OdmMb4aulUvB4ryn4oeaM6KW6Iz1o/BO/uKnzNqG8tjMpv+vepGx2Em0WyMfjEHlRsNFkFj7LQ4zW94/MhrTWrjZ3ko84uqNWL/63Zwbdqa6q3S4TyMuGGWET7HcX1rxucMcglKF1jkuqEESiwwm6WmW/fim4m6N2lI0hkymjYLM6JlR7ZSXd2E+2dVMOC6Nd9w7Sd2UB7CVBL1zbSYDxEr0Vo6RNbWk2oYEk3t3MvJzMzAZQvQhU8pU31fNZ4CneQpIx1C/nLzFUFG0y4lQSponmxGmHnA9KgnjU/c12gCG0l6V9lQgR6uZvAKOpS6fUHU45hOI4XiyOEWIkIS7FLHu5hks019ge/ULO3N5TAZLLxQ3mWdPnFq1PZ0vg756YENhIqBDV0LL0/QahwHFLq1HQWiRDRYLzSP93//flGZTH6bNe3qh12/rq6pxCgV+rVTrWKFclpDZLH1lcRMSXd+CFZcO1CUOzPBD+oEfx2ZhWDbb/atu6Zp+oJZNYSdTc+jbyuV3+uhGihsqLH277ubqcRSCYAXU6YOw3komGl6/OLxnSBXWJQnFcspyg+3ao1bhEowcWnm7hWM74cBtjIJS2rNCDAiC2AGcf6JgOs="
branches:
  only:
    - master
